name: EB deploy
on:
  push:
  # Specify the desired trigger branch
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      PRODUCTION_ENV_NAME: ${{ secrets.PRODUCTION_ENV_NAME }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      # Specify the relevant steps to build / package and ship 
      # the app / site below
      - name: Install Dependencies
        run: |
          npm install
      - name: Build and Zip
        run: |
          BUILD_ENV="production" npm run build
          npm run zip
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy ${{ secrets.PRODUCTION_ENV_NAME }}
