name: Restore Storybook URL

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: url.txt
          key: ${{ github.ref_name }}-storybook-url

      - name: Do stuff
        if: steps.cache.outputs.cache-hit == 'true'
        run: cat url.txt
